<?php
    include 'connect.php';
    $id = $_GET['idDoador'];
    $sql="select * from Doador where idDoador={$id}";
    $query= mysqli_query($con, $sql);
    $produto=mysqli_fetch_assoc($query);
?>

<h1> Doadores </h1>
        <form method="POST" action="#" enctype="multipart/form-data">
            <table>
                <tr>
                    <td> 
                       <!-- readonly comando para deixar id modo nao editavel, apenas visualização -->
                       Id:
                       <input readonly="readonly" type="text"  name="id" value="<?php echo $Doador['IdDoador']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        primeiro nome: <!--retorna nome e id do produto esta funçao-->
                        <input type="text" name="PrimeiroNome" value="<?php echo $Doador['PrimeiroNome']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        ultimo nome: 
                        <input type="txt" name="UltimoNome" value="<?php echo  $Doador['UltimoNome']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        Email: 
                        <input type="txt" name="Email" value="<?php echo  $Doador['Email']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        Telefone: 
                        <input type="txt" name="Telefone" value="<?php echo  $Doador['Telefone']?>">
                    </td>
                </tr>
                <tr>
                    <td>

                        Cidade: 
                        <input type="txt" name="Cidade" value="<?php echo  $Doador['Cidade']?>">
                    </td>
                </tr>

                <tr>
                    <td>
                        Bairro: 
                        <input type="txt" name="Bairro" value="<?php echo  $Doador['Bairro']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        Rua: 
                        <input type="txt" name="Rua" value="<?php echo  $Doador['Rua']?>">
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="submit" name="sub">
                    </td>
                </tr>            
            </table>
        </form> 